config/routes.rb
Rails.application.routes.draw do
  resources :tareas

  root 'tareas#index'

end

app/models/tarea.rb
class Tarea < ActiveRecord::Base
	validates :titulo, presence: true, length: { minimum: 5 }
	validates :descripcion, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  def index
	@tarea = Tarea.all()
  end

  def new
  	@tarea = Tarea.new

  end

  def create
  	@tarea = Tarea.new(params.require(:tarea).permit(:titulo, :descripcion))

  	@tarea.titulo = params[:tarea][:titulo]
  	@tarea.descripcion = params[:tarea][:descripcion]

  	puts @tarea
  	puts @tarea.titulo
  	puts @tarea.descripcion

 	@tarea.save
  	redirect_to @tarea
	
  end


  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Organizador</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tareas/_formulario_guardar.html.erb
<%= form_for @tarea do |f| %> 
   <p> 
      <%= f.label :tituloLabel, "Título" %>
      <br />
      <%= f.text_field :titulo, {:value => @titulo} %>
   </p>
   <p> 
      <%= f.label :descripcionLabel, "Descripción" %>
      <br />
      <%= f.text_field :descripcion, {:value => @descripcion} %>
   </p>
   
   <p>
      <%= f.submit "Enviar" %> <%= link_to "Cancelar", tareas_path %>
   </p>
<% end %>

app/views/tareas/create.html.erb
<h1>Tareas#create</h1>
<p>Find me in app/views/tareas/create.html.erb</p>

app/views/tareas/index.html.erb
<h1>Tareas listar</h1>

<ul>
   <% @tarea.each do |t| %>
   <p>
      <h3> <%= t.titulo %>
      	<%= t.descripcion %> </h3>
   </p>
   <% end %>
</ul>

<p><%=link_to "Crear nueva tarea", new_tarea_path%></p>

app/views/tareas/new.html.erb
<h1>Tareas#new</h1>
<%= render :partial => "formulario_guardar.html" %>

app/views/tareas/show.html.erb
<h1>Tareas#show</h1>